---
dellos_bgp:
  Spine1:
    asn: 64601
    router_id: 192.168.3.100
    #maxpath_ibgp: 2
    maxpath_ebgp: 2
    graceful_restart:
      state: present
    best_path:
      as_path: multipath-relax
      ignore_router_id: true
    #med:
      #- attribute: confed
        #state: present
      #- attribute: missing-as-best
        #state: present
    ipv4_network:
      - address: 102.1.1.0/30
        state: present
    neighbor:
      - name: spine-leaf
        type: peergroup
        type_options: 
        - option: fall-over
        - option: advertisement-interval 
        - option: nshutdown
        - option: bfd
      - ip: 192.168.1.1
        type: ipv4
        remote_asn: 64704
        peergroup: spine-leaf
        peergroup_state: present
        type_options:
        - option: nshutdown
      - ip: 192.168.1.3
        type: ipv4
        remote_asn: 64703
        peergroup: spine-leaf
        peergroup_state: present
        type_options:
        - option: nshutdown
    redistribute:
      - route_type: connected
        state: present
        address_type: ipv4
        route_map: present
  Leaf1:
    asn: 64703
    router_id: 192.168.3.101
    #maxpath_ibgp: 2
    maxpath_ebgp: 2
    graceful_restart:
      state: present
    best_path:
      as_path: multipath-relax
      ignore_router_id: true
    #med:
      #- attribute: confed
        #state: present
      #- attribute: missing-as-best
        #state: present
    #ipv4_network:
      #- address: 102.1.1.0/30
        #state: present
    neighbor:
      - name: spine-leaf
        type: peergroup
        type_options: 
        - option: fall-over
        - option: advertisement-interval 
        - option: nshutdown
        - option: bfd
      - ip: 192.168.1.2
        type: ipv4
        remote_asn: 64601
        peergroup: spine-leaf
        peergroup_state: present
        type_options:
        - option: nshutdown
    redistribute:
      - route_type: connected
        state: present
        address_type: ipv4
        route_map: present
  Leaf2:
    asn: 64704
    router_id: 192.168.3.102
    #maxpath_ibgp: 2
    maxpath_ebgp: 2
    graceful_restart:
      state: present
    best_path:
      as_path: multipath-relax
      ignore_router_id: true
    #med:
      #- attribute: confed
        #state: present
      #- attribute: missing-as-best
        #state: present
    #ipv4_network:
      #- address: 102.1.1.0/30
        #state: present
    neighbor:
      - name: spine-leaf
        type: peergroup
        type_options: 
        - option: fall-over
        - option: advertisement-interval 
        - option: nshutdown
        - option: bfd
      - ip: 192.168.1.0
        type: ipv4
        remote_asn: 64601
        peergroup: spine-leaf
        peergroup_state: present
        type_options:
        - option: nshutdown
    redistribute:
      - route_type: connected
        state: present
        address_type: ipv4
        route_map: present
